In [1]:
import numpy as np
import pandas as pd
import requests
import os
import datetime

import filosofi
import dvf

In [10]:
filosofi_df = filosofi.main()
filosofi_df.head()

,echelle,code_INSEE,annee,Menages_fiscaux,Nb_personnes,Unites_conso,Taux_pauvrete,Salaire_D1,Salaire_median,Salaire_D9,...,Part_salaires,Part_acti_non_salar,Part_chomage,Part_prest_soc,Part_prest_famil,Part_prest_logt,Part_min_sociaux,Part_pensions_retraites,Part_patrimoine,Part_impots
0,COM,51414,2025,70.0,167.0,112.9,NaN,NaN,26680.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COM,87178,2025,1248.0,2831.0,1947.6,10.0,14000.0,23470.0,34120.0,...,65.7,3.4,2.6,3.7,1.6,0.6,1.5,34.6,4.1,-14.1
2,COM,77349,2025,2463.0,6606.0,4276.6,7.0,15910.0,26870.0,39690.0,...,80.7,2.3,2.7,3.6,2.1,0.4,1.1,22.7,4.7,-16.7
3,AAV2020,324,2025,9302.0,19124.0,13700.8,15.7,12160.0,21230.0,33730.0,...,52.7,6.2,3.0,6.2,1.9,1.2,3.1,35.8,9.0,-12.9
4,ZE2020,2802,2025,40957.0,87445.0,61739.7,12.5,13000.0,21800.0,34230.0,...,56.0,7.1,2.2,5.1,1.9,0.9,2.3,34.4,8.3,-13.1

In [ ]:
files_list = [os.path.join("data_dvf", file) for file in os.listdir("data_dvf")]

mask_funcs = [
    # only houses and appartments
    lambda df: df["Code type local"].isin([1, 2]),
    # sales take place in Rhone department
    lambda df: df["Code departement"] == "69"
]

all_chunks = [
    dvf.dvf_reformat(chunk) 
    for file_path in files_list 
    for chunk in dvf.dvf_extract(file_path, mask_funcs)]

dvf_df = pd.concat(all_chunks)
dvf_df.head()

data_dvf/ValeursFoncieres-2025-S1.txt
Memory before reading: 108.08 Mb
data_dvf/ValeursFoncieres-2023.txt
Memory before reading: 150.91 Mb
data_dvf/ValeursFoncieres-2021.txt
Memory before reading: 201.11 Mb
data_dvf/ValeursFoncieres-2022.txt
Memory before reading: 212.23 Mb
data_dvf/ValeursFoncieres-2024.txt
Memory before reading: 232.56 Mb

,Date mutation,Année,Nature mutation,Adresse,Code voie,Code postal,Commune,Code commune,Code departement,Prefixe de section,...,No Volume,Nombre de lots,Code type local,Type local,Nombre pieces principales,Valeur fonciere,Surface reelle bati,Surface terrain,Surface Carrez,Prix au m2
932342,2025-01-03,2025,Vente,86 RUE DES COLLONGES 69230 SAINT-GENIS-LAVAL,0290,69230,SAINT-GENIS-LAVAL,204,69,NaN,...,NaN,2,2,Appartement,4,225000.00,80.0,NaN,73.05,2812.500000
932346,2025-01-06,2025,Vente,20 RUE DE FRANCHE COMTE 69110 SAINTE FOY LES LYON,0460,69110,SAINTE FOY LES LYON,202,69,NaN,...,NaN,2,2,Appartement,3,202256.48,66.0,NaN,61.41,3064.492121
932348,2025-01-07,2025,Vente,189 RUE PAUL CLAUDEL 69400 VILLEFRANCHE,1383,69400,VILLEFRANCHE,264,69,NaN,...,NaN,2,2,Appartement,4,145000.00,68.0,NaN,68.64,2132.352941
932358,2025-01-02,2025,Vente,116 RUE DU FORGERON 69220 BELLEVILLE-EN-BEAUJO...,0062,69220,BELLEVILLE-EN-BEAUJOLAIS,19,69,211.0,...,NaN,0,1,Maison,3,277340.00,100.0,537.0,0.00,2773.400000
932359,2025-01-02,2025,Vente,116 RUE DU FORGERON 69220 BELLEVILLE-EN-BEAUJO...,0062,69220,BELLEVILLE-EN-BEAUJOLAIS,19,69,211.0,...,NaN,0,1,Maison,3,277340.00,100.0,360.0,0.00,2773.400000